## Python
Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable. As an example, here is an implementation of the classic quicksort algorithm in Python:

In [1]:
def quicksort(arr):
    if len(arr)<=1:
        return arr
    pivot=arr[len(arr)//2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)
print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


## Basic data types
Like most languages, Python has a number of basic types including integers, floats, booleans, and strings. These data types behave in ways that are familiar from other programming languages.

Numbers: Integers and floats work as you would expect from other languages:

In [2]:
x=3

In [3]:
print(type(x))

<class 'int'>


In [4]:
print(x)

3


In [5]:
print(x+1)

4


In [6]:
print(x-1)

2


In [7]:
print(x**2)

9


In [8]:
x+=1

In [9]:
print(x)

4


In [10]:
x*=2

In [11]:
print(x)

8


In [12]:
y=2.5

In [13]:
print(type(y))

<class 'float'>


In [14]:
print(y,y+1,y*2,y**2)

2.5 3.5 5.0 6.25


## Booleans: 
Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.):

In [15]:
T= True
F= False

In [16]:
print(type(T))

<class 'bool'>


In [17]:
print(type(F))

<class 'bool'>


In [18]:
print(T and F)

False


In [19]:
print(F and T)

False


In [20]:
print(T or F)

True


In [21]:
print(not T)

False


In [22]:
print(T!= F)

True


## Strings:
Python has great support for strings:

In [23]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.

In [24]:
print(hello)

hello


In [25]:
print(world)

world


In [26]:
print(len(hello))

5


In [27]:
hw= hello + ''+ world # String concatenation

In [28]:
print(hw)

helloworld


In [29]:
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting

In [30]:
print(hw12)

hello world 12


In [31]:
S= "hello"

In [32]:
print(S.capitalize()) # Capitalize a string; prints "Hello"

Hello


In [33]:
print(S.upper())    # Convert a string to uppercase; prints "HELLO"

HELLO


In [34]:
print(S.rjust(7))   # Right-justify a string, padding with spaces; prints "  hello"

  hello


In [35]:
print(S.replace('1','ell'))    #Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"

hello


In [36]:
print(S.center(7))           # Center a string, padding with spaces; prints " hello "

 hello 


In [37]:
print('world'.strip())

world


## Containers
Python includes several built-in container types: lists, dictionaries, sets, and tuples.


## Lists
A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [38]:
list1= [3,2,1]

In [39]:
print(list1,list1[2])

[3, 2, 1] 1


In [40]:
print(list1[-1])

1


In [41]:
list1[2]='King'

In [42]:
print(list1)

[3, 2, 'King']


In [43]:
list1.append('Vijay')

In [44]:
print(list1)

[3, 2, 'King', 'Vijay']


In [45]:
x=list1.pop()

In [46]:
print(x)

Vijay


In [47]:
print(x,list1)

Vijay [3, 2, 'King']


## Slicing: 
In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [48]:
nums = list(range(5))

In [49]:
print(nums)

[0, 1, 2, 3, 4]


In [50]:
print(nums[2:4])

[2, 3]


In [51]:
print(nums[2:])

[2, 3, 4]


In [52]:
print(nums[:2])

[0, 1]


In [53]:
print(nums[:])

[0, 1, 2, 3, 4]


In [54]:
print(nums[:-1])

[0, 1, 2, 3]


In [55]:
nums[2:4]=[8,9]

In [56]:
print(nums)

[0, 1, 8, 9, 4]


## Loops: 
You can loop over the elements of a list like this:

In [57]:
animals=['Cat','Dog','Monkey']

In [58]:
for animal in animals:
    print(animal)

Cat
Dog
Monkey


If you want access to the index of each element within the body of a loop, use the built-in enumerate function:

In [59]:
animals = ['cat', 'dog', 'monkey']

In [60]:
for idx,animal in enumerate(animals):
    print('@%d: %s' % (idx + 1, animal))

@1: cat
@2: dog
@3: monkey


## List comprehensions: 
When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [61]:
nums=[0,1,2,3,4]
square=[]

In [62]:
for x in nums:
    square.append(x**2)
print(square)

[0, 1, 4, 9, 16]


You can make this code simpler using a list comprehension:

In [63]:
num=[4,5,6,7,8]
squares=[x**2 for x in num]
print(squares)

[16, 25, 36, 49, 64]


List comprehensions can also contain conditions:

In [64]:
nums = [0, 1, 2, 3, 4]
even_squares=[x**2 for x in nums if x%2==0]
print(even_squares)

[0, 4, 16]


In [65]:
odd_squares=[x**2 for x in nums if x%2!= 0]
print(odd_squares)

[1, 9]


## Dictionaries
A dictionary stores (key, value) pairs, similar to a Map in Java or an object in Javascript. You can use it like this:

In [66]:
d = {'cat': 'cute', 'dog': 'furry'}

In [67]:
print(d['cat'])

cute


In [68]:
print(d['dog'])

furry


In [69]:
print('cat' in d)

True


In [70]:
d['fish']='wet'

In [71]:
print(d['fish'])

wet


In [72]:
print(d['fish'])

wet


In [73]:
print(d.get('monkey','N/A'))

N/A


In [74]:
print(d.get('fish','N/A'))

wet


In [75]:
del d['fish']

In [76]:
print(d)

{'cat': 'cute', 'dog': 'furry'}


In [77]:
print(d.get('fish','N/A'))

N/A


## Loops: 
It is easy to iterate over the keys in a dictionary:

In [78]:
d={'person':2,'cat':4,'spider':8}

In [79]:
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


If you want access to keys and their corresponding values, use the items method:

In [80]:
for animal,legs in d.items():
     print('A %s has %d legs' % (animal, legs))


A person has 2 legs
A cat has 4 legs
A spider has 8 legs


## Dictionary comprehensions:
These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [81]:
nums=[0,1,2,3,4]
even_num_to_square={x: x**2 for x in nums if x%2==0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


In [82]:
odd_num_to_square={x: x**2 for x in nums if x%2!=0}
print(odd_num_to_square)

{1: 1, 3: 9}


## Sets
A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [83]:
animals = {'cat', 'dog'}

In [84]:
print('cat' in animals)

True


In [85]:
print('dog' in animals)

True


In [86]:
print('fish' in animals)

False


In [87]:
animals.add('fish')

In [88]:
print('fish'in animals)

True


In [89]:
print(len(animals))

3


In [90]:
animals.remove('cat')

In [91]:
print(animals)

{'fish', 'dog'}


In [92]:
print(len(animals))

2


## Loops: 
Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [93]:
animals = {'cat', 'dog', 'fish'}

In [94]:
for idx,animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

#1: cat
#2: fish
#3: dog


## Set comprehensions: 
Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [95]:
from math import sqrt

In [96]:
num1={int(sqrt(x)) for x in range(30)}
print(num1)

{0, 1, 2, 3, 4, 5}


## Tuples
A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [97]:
d={(x,x+1): x for x in range(10)}

In [98]:
print(d)

{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}


In [99]:
t=(5,6)

In [100]:
print(t)

(5, 6)


In [101]:
print(d[t])

5


In [102]:
print(d[1,2])

1


## Functions
Python functions are defined using the def keyword. For example:

In [103]:
def sign(x):
    if x>0:
        return'positive'
    elif x<0:
        return'negative'
    else:
        return'neutral'

In [104]:
for x in [1,0,-1]:
    print(sign(x))

positive
neutral
negative


We will often define functions to take optional keyword arguments, like this:

In [105]:
def hello(name,loud=False):
    if loud:
        print('Hello,%s!'%name.upper())
    else:
        print('Hello,%s'%name)

In [106]:
hello('vijay')

Hello,vijay


In [107]:
hello('arvind',loud=True)

Hello,ARVIND!


## Classes
The syntax for defining classes in Python is straightforward:

In [108]:
class Greeter(object):
    # Constructor
    def _init_(self,name):
        self.name = name # Create an instance variable
    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)


## Numpy
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

## Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [109]:
import numpy as np

In [110]:
a=np.array([1,2,3])

In [111]:
print(type(a))

<class 'numpy.ndarray'>


In [112]:
print(a.shape)

(3,)


In [113]:
print(a[0],a[1],a[2])

1 2 3


In [114]:
a[0]=5

In [115]:
print(a[0])

5


In [116]:
b=np.array([[1,2,3],[4,5,6]])

In [117]:
print(b.shape)

(2, 3)


In [118]:
print(b[0,0],b[0,1],b[0,2])

1 2 3


In [119]:
print(b[1,0],b[1,1],b[1,2])

4 5 6


Numpy also provides many functions to create arrays:

In [120]:
a=np.zeros((2,2))# Create an array of all zeros

In [121]:
print(a)

[[0. 0.]
 [0. 0.]]


In [122]:
f = np.ones((1,2))    # Create an array of all ones
print(f)

[[1. 1.]]


In [123]:
c=np.full((2,2),7)# Create a constant array

In [124]:
print(c)

[[7 7]
 [7 7]]


In [125]:
d=np.eye(2) # Create a 2x2 identity matrix

In [126]:
print(d)

[[1. 0.]
 [0. 1.]]


In [127]:
e=np.random.random((2,2)) # Create an array filled with random values

In [128]:
print(e)

[[0.20739297 0.60839086]
 [0.36987561 0.83637909]]


## Array indexing
Numpy offers several ways to index into arrays.

## Slicing:
Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [129]:
x=np.array([[1,2,3,4],[6,7,8,9],[11,12,13,14]])

In [130]:
z=x[:2,1:3]  # Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):

In [131]:
print(z)

[[2 3]
 [7 8]]


In [132]:
k=np.full((3,4),7) # Create the following rank 2 array with shape (3, 4)

In [133]:
print(k)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [134]:
print(x[0,1])

2


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [135]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [136]:
row_r1=a[1,:] # Rank 1 view of the second row of a

In [137]:
print(row_r1)

[5 6 7 8]


In [138]:
row_r1

array([5, 6, 7, 8])

In [139]:
row_r2=a[1:2,:] # Rank 2 view of the second row of a

In [140]:
row_r2 

array([[5, 6, 7, 8]])

In [141]:
print(row_r1,row_r1.shape)

[5 6 7 8] (4,)


In [142]:
print(row_r2,row_r2.shape)

[[5 6 7 8]] (1, 4)


In [143]:
col_r1=a[:,1]

In [144]:
col_r2=a[:,1:2]

In [145]:
print(col_r1,col_r1.shape)

[ 2  6 10] (3,)


In [146]:
print(col_r2,col_r2.shape)

[[ 2]
 [ 6]
 [10]] (3, 1)


## Integer array indexing: 
When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [147]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [148]:
print(a[[0,1,2],[0,1,0]]) # An example of integer array indexing.
# The returned array will have shape (3,) and

[1 4 5]


In [149]:
print(a[[0,1,2]]) # The returned array will have shape (2,3) and

[[1 2]
 [3 4]
 [5 6]]


In [150]:
print(np.array([a[(0,1)],a[(1,0)],a[(2,0)]]))

[2 3 5]


In [151]:
print(a[[0,0],[1,1]])# When using integer array indexing, you can reuse the same
                     # element from the source array:

[2 2]


In [152]:
print(np.array([a[0,1],a[0,1]])) # Equivalent to the previous integer array indexing example

[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [153]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [154]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [155]:
b=np.array([0,1,0,2])

In [156]:
print(b)

[0 1 0 2]


In [157]:
print(a[np.arange(4),b]) # Select one element from each row of a using the indices in b

[ 1  5  7 12]


In [158]:
a[np.arange(4),b]+=10

In [159]:
print(a)

[[11  2  3]
 [ 4 15  6]
 [17  8  9]
 [10 11 22]]


## Boolean array indexing:
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [160]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [161]:
bool_idx=(a>2)  # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

In [162]:
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [163]:
print(a[bool_idx])

[3 4 5 6]


In [164]:
print(a[a>2])    # We can do all of the above in a single concise statement:

[3 4 5 6]


## Datatypes
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [165]:
x=np.array([1,2])

In [166]:
print(x.dtype)

int32


In [167]:
x=np.array([1.0,2.0])

In [168]:
print(x.dtype)

float64


In [169]:
x=np.array([1,2],dtype=np.int64)

In [170]:
print(x.dtype) # Force a particular datatype

int64


## Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [171]:
x=np.array([[1,2],[3,4]],dtype=np.int64)

In [172]:
y=np.array([[6,7],[8,9]],dtype=np.int64)

In [173]:
print(x+y)

[[ 7  9]
 [11 13]]


In [174]:
print(np.add(x,y))

[[ 7  9]
 [11 13]]


In [175]:
print(x-y)

[[-5 -5]
 [-5 -5]]


In [176]:
print(np.subtract(x,y))

[[-5 -5]
 [-5 -5]]


In [177]:
print(np.subtract(y,x))

[[5 5]
 [5 5]]


In [178]:
print(x/y)

[[0.16666667 0.28571429]
 [0.375      0.44444444]]


In [179]:
print(np.divide(x,y))

[[0.16666667 0.28571429]
 [0.375      0.44444444]]


In [180]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


We use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [181]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [182]:
v = np.array([9,10])
w = np.array([11, 12])

In [183]:
print(v.dot(w)) # Inner product of vectors; both produce 219

219


In [184]:
print(np.dot(v,w))

219


In [185]:
print(x.dot(v)) # Matrix / vector product; both produce the rank 1 array [29 67]

[29 67]


In [186]:
print(np.dot(x,v))

[29 67]


In [187]:
print(x.dot(y))# Matrix / matrix product; both produce the rank 2 array

[[19 22]
 [43 50]]


In [188]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:

In [189]:
x=np.array([[(1,2),(3,4)]])

In [190]:
print(np.sum(x))     # Compute sum of all elements; prints "10"

10


In [192]:
print(np.sum(x,axis=0))   # Compute sum of each column; prints "[4 6]"

[[1 2]
 [3 4]]


In [193]:
print(np.sum(x,axis=1))   # Compute sum of each row; prints "[3 7]"

[[4 6]]


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [194]:
print(x)

[[[1 2]
  [3 4]]]


In [195]:
print(x,T)

[[[1 2]
  [3 4]]] True


In [197]:
v=np.array([1,2,3])     # Note that taking the transpose of a rank 1 array does nothing:

In [198]:
print(v)

[1 2 3]


In [199]:
print(v,T)

[1 2 3] True


## Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [201]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [202]:
v = np.array([1, 0, 1])

In [203]:
y=np.empty_like(x)  # Create an empty matrix with the same shape as x

In [204]:
for i in range(4):  # Add the vector v to each row of the matrix x with an explicit loop
    y[1,:]=x[1,:]+v

In [205]:
print(y)

[[0 0 0]
 [5 5 7]
 [0 0 0]
 [0 0 0]]


This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [206]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [207]:
vv=np.tile(v,(4,1))    # Stack 4 copies of v on top of each other

In [208]:
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [209]:
y=x+vv

In [210]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [211]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [212]:
y=x+v   # Add v to each row of x using broadcasting

In [213]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

## Broadcasting two arrays together follows these rules:

1.If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2.The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3.The arrays can be broadcast together if they are compatible in all dimensions.
4.After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5.In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.

In [214]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

In [215]:
print(np.reshape(v,(3,1))*w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [216]:
x = np.array([[1,2,3], [4,5,6]])

In [217]:
print(x+v)

[[2 4 6]
 [5 7 9]]


In [218]:
print((x.T+w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [219]:
print(x+np.reshape(w,(2,1)))

[[ 5  6  7]
 [ 9 10 11]]


In [220]:
print(x*2)

[[ 2  4  6]
 [ 8 10 12]]
